# Generated by tools\Build-PrivateUnitTests.ps1. Re-run to regenerate.
BeforeAll {

$ProjectRoot   = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$RelativePath  = 'Private\Complete-GELogSession.ps1'
$SourcePath    = Join-Path $ProjectRoot $RelativePath
}

Describe 'Complete-GELogSession (private contract)' {

    BeforeAll {
        $script:Ast = $null
        $script:Fn  = $null
        if (Test-Path -LiteralPath $SourcePath -PathType Leaf) {
            $tokens = $null; $errors = $null
            $script:Ast = [System.Management.Automation.Language.Parser]::ParseFile($SourcePath, [ref]$tokens, [ref]$errors)
            $script:Fn  = @($script:Ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $true)) | Select-Object -First 1
        }
    }

    It 'source file exists at the expected location' {
        Test-Path -LiteralPath $SourcePath -PathType Leaf | Should -Be $true
    }

    It 'declares a function whose name matches the file name' {
        $script:Fn.Name | Should -Be 'Complete-GELogSession'
    }

    It 'name uses the GE prefix convention' {
        $script:Fn.Name | Should -Match '^[A-Za-z]+-GE[A-Za-z0-9]+$'
    }

    It 'declares [CmdletBinding()]' {
        $hasBinding = $false
        if ($script:Fn.Body.ParamBlock -and $script:Fn.Body.ParamBlock.Attributes) {
            foreach ($attr in $script:Fn.Body.ParamBlock.Attributes) {
                if ($attr.TypeName.Name -eq 'CmdletBinding') { $hasBinding = $true }
            }
        }
        $hasBinding | Should -Be $true
    }

    It 'declares the -Path parameter' {
        $names = @()
        if ($script:Fn.Body.ParamBlock -and $script:Fn.Body.ParamBlock.Parameters) {
            $names = @($script:Fn.Body.ParamBlock.Parameters | ForEach-Object { $_.Name.VariablePath.UserPath })
        }
        $names -contains 'Path' | Should -Be $true
    }

    It '-Path is mandatory' {
        $param = $script:Fn.Body.ParamBlock.Parameters | Where-Object { $_.Name.VariablePath.UserPath -eq 'Path' } | Select-Object -First 1
        $isMandatory = $false
        foreach ($attr in $param.Attributes) {
            if ($attr.TypeName.Name -eq 'Parameter') {
                foreach ($na in $attr.NamedArguments) {
                    if ($na.ArgumentName -eq 'Mandatory') { $isMandatory = $true }
                }
            }
        }
        $isMandatory | Should -Be $true
    }

    It 'declares the -Outcome parameter' {
        $names = @()
        if ($script:Fn.Body.ParamBlock -and $script:Fn.Body.ParamBlock.Parameters) {
            $names = @($script:Fn.Body.ParamBlock.Parameters | ForEach-Object { $_.Name.VariablePath.UserPath })
        }
        $names -contains 'Outcome' | Should -Be $true
    }

    It '-Outcome is mandatory' {
        $param = $script:Fn.Body.ParamBlock.Parameters | Where-Object { $_.Name.VariablePath.UserPath -eq 'Outcome' } | Select-Object -First 1
        $isMandatory = $false
        foreach ($attr in $param.Attributes) {
            if ($attr.TypeName.Name -eq 'Parameter') {
                foreach ($na in $attr.NamedArguments) {
                    if ($na.ArgumentName -eq 'Mandatory') { $isMandatory = $true }
                }
            }
        }
        $isMandatory | Should -Be $true
    }

    It '-Outcome accepts only the documented values' {
        $param = $script:Fn.Body.ParamBlock.Parameters | Where-Object { $_.Name.VariablePath.UserPath -eq 'Outcome' } | Select-Object -First 1
        $values = @()
        foreach ($attr in $param.Attributes) {
            if ($attr.TypeName.Name -eq 'ValidateSet') {
                foreach ($pa in $attr.PositionalArguments) {
                    if ($pa.Value) { $values += $pa.Value }
                }
            }
        }
        $values -contains 'SUCCESS' | Should -Be $true
        $values -contains 'FAILURE' | Should -Be $true
    }

    It 'declares the -UserMessage parameter' {
        $names = @()
        if ($script:Fn.Body.ParamBlock -and $script:Fn.Body.ParamBlock.Parameters) {
            $names = @($script:Fn.Body.ParamBlock.Parameters | ForEach-Object { $_.Name.VariablePath.UserPath })
        }
        $names -contains 'UserMessage' | Should -Be $true
    }

    It 'declares the -ErrorMessage parameter' {
        $names = @()
        if ($script:Fn.Body.ParamBlock -and $script:Fn.Body.ParamBlock.Parameters) {
            $names = @($script:Fn.Body.ParamBlock.Parameters | ForEach-Object { $_.Name.VariablePath.UserPath })
        }
        $names -contains 'ErrorMessage' | Should -Be $true
    }

    It 'has comment-based help with .SYNOPSIS' {
        $body   = Get-Content -LiteralPath $SourcePath -Raw
        $hasCbh = ($body -match '(?ms)<#.*?\.SYNOPSIS\s+\S.*?#>')
        $hasCbh | Should -Be $true
    }

}
