# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'

Describe 'New-Release (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'New-Release').Count | Should Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'New-Release'
        $cmd.CmdletBinding | Should Be $true
    }

    It 'supports ShouldProcess (-WhatIf and -Confirm available)' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('WhatIf')  | Should Be $true
        $cmd.Parameters.ContainsKey('Confirm') | Should Be $true
    }

    It 'declares the -Version parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('Version') | Should Be $true
    }

    It '-Version is mandatory' {
        $cmd = Get-Command 'New-Release'
        $attrs = $cmd.Parameters['Version'].Attributes
        $paramAttr = $attrs | Where-Object { $_.GetType().Name -eq 'ParameterAttribute' } | Select-Object -First 1
        $paramAttr.Mandatory | Should Be $true
    }

    It 'declares the -Note parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('Note') | Should Be $true
    }

    It '-Note is mandatory' {
        $cmd = Get-Command 'New-Release'
        $attrs = $cmd.Parameters['Note'].Attributes
        $paramAttr = $attrs | Where-Object { $_.GetType().Name -eq 'ParameterAttribute' } | Select-Object -First 1
        $paramAttr.Mandatory | Should Be $true
    }

    It 'declares the -NoPush parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('NoPush') | Should Be $true
    }

    It '-NoPush is a switch parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters['NoPush'].ParameterType.Name | Should Be 'SwitchParameter'
    }

    It 'declares the -Force parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('Force') | Should Be $true
    }

    It '-Force is a switch parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters['Force'].ParameterType.Name | Should Be 'SwitchParameter'
    }

    It 'declares the -LogPath parameter' {
        $cmd = Get-Command 'New-Release'
        $cmd.Parameters.ContainsKey('LogPath') | Should Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'New-Release' -ErrorAction SilentlyContinue
        $help.Synopsis | Should Not BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'New-Release' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should Be $true
    }
}
