# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'

Describe 'Restore-File (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Restore-File').Count | Should Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Restore-File'
        $cmd.CmdletBinding | Should Be $true
    }

    It 'supports ShouldProcess (-WhatIf and -Confirm available)' {
        $cmd = Get-Command 'Restore-File'
        $cmd.Parameters.ContainsKey('WhatIf')  | Should Be $true
        $cmd.Parameters.ContainsKey('Confirm') | Should Be $true
    }

    It 'declares the -Path parameter' {
        $cmd = Get-Command 'Restore-File'
        $cmd.Parameters.ContainsKey('Path') | Should Be $true
    }

    It '-Path is mandatory' {
        $cmd = Get-Command 'Restore-File'
        $attrs = $cmd.Parameters['Path'].Attributes
        $paramAttr = $attrs | Where-Object { $_.GetType().Name -eq 'ParameterAttribute' } | Select-Object -First 1
        $paramAttr.Mandatory | Should Be $true
    }

    It 'declares the -LogPath parameter' {
        $cmd = Get-Command 'Restore-File'
        $cmd.Parameters.ContainsKey('LogPath') | Should Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Restore-File' -ErrorAction SilentlyContinue
        $help.Synopsis | Should Not BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Restore-File' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should Be $true
    }
}
