# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.
BeforeAll {

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'
}

Describe 'Set-Ssh (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Set-Ssh').Count | Should -Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Set-Ssh'
        $cmd.CmdletBinding | Should -Be $true
    }

    It 'supports ShouldProcess (-WhatIf and -Confirm available)' {
        $cmd = Get-Command 'Set-Ssh'
        $cmd.Parameters.ContainsKey('WhatIf')  | Should -Be $true
        $cmd.Parameters.ContainsKey('Confirm') | Should -Be $true
    }

    It 'declares the -RemoteName parameter' {
        $cmd = Get-Command 'Set-Ssh'
        $cmd.Parameters.ContainsKey('RemoteName') | Should -Be $true
    }

    It 'declares the -RemoteUrl parameter' {
        $cmd = Get-Command 'Set-Ssh'
        $cmd.Parameters.ContainsKey('RemoteUrl') | Should -Be $true
    }

    It 'declares the -LogPath parameter' {
        $cmd = Get-Command 'Set-Ssh'
        $cmd.Parameters.ContainsKey('LogPath') | Should -Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Set-Ssh' -ErrorAction SilentlyContinue
        $help.Synopsis | Should -Not -BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Set-Ssh' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should -Be $true
    }
}
