# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.
BeforeAll {

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'
}

Describe 'Show-Releases (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Show-Releases').Count | Should -Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Show-Releases'
        $cmd.CmdletBinding | Should -Be $true
    }

    It 'declares the -Pattern parameter' {
        $cmd = Get-Command 'Show-Releases'
        $cmd.Parameters.ContainsKey('Pattern') | Should -Be $true
    }

    It 'declares the -Count parameter' {
        $cmd = Get-Command 'Show-Releases'
        $cmd.Parameters.ContainsKey('Count') | Should -Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Show-Releases' -ErrorAction SilentlyContinue
        $help.Synopsis | Should -Not -BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Show-Releases' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should -Be $true
    }
}
