# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'

Describe 'Show-History (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Show-History').Count | Should Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Show-History'
        $cmd.CmdletBinding | Should Be $true
    }

    It 'declares the -Count parameter' {
        $cmd = Get-Command 'Show-History'
        $cmd.Parameters.ContainsKey('Count') | Should Be $true
    }

    It 'declares the -Graph parameter' {
        $cmd = Get-Command 'Show-History'
        $cmd.Parameters.ContainsKey('Graph') | Should Be $true
    }

    It '-Graph is a switch parameter' {
        $cmd = Get-Command 'Show-History'
        $cmd.Parameters['Graph'].ParameterType.Name | Should Be 'SwitchParameter'
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Show-History' -ErrorAction SilentlyContinue
        $help.Synopsis | Should Not BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Show-History' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should Be $true
    }
}
