# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.
BeforeAll {

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'
}

Describe 'Show-Change (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Show-Change').Count | Should -Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Show-Change'
        $cmd.CmdletBinding | Should -Be $true
    }

    It 'declares the -Path parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters.ContainsKey('Path') | Should -Be $true
    }

    It 'declares the -NextSave parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters.ContainsKey('NextSave') | Should -Be $true
    }

    It '-NextSave is a switch parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters['NextSave'].ParameterType.Name | Should -Be 'SwitchParameter'
    }

    It 'declares the -Compact parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters.ContainsKey('Compact') | Should -Be $true
    }

    It '-Compact is a switch parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters['Compact'].ParameterType.Name | Should -Be 'SwitchParameter'
    }

    It 'declares the -LogPath parameter' {
        $cmd = Get-Command 'Show-Change'
        $cmd.Parameters.ContainsKey('LogPath') | Should -Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Show-Change' -ErrorAction SilentlyContinue
        $help.Synopsis | Should -Not -BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Show-Change' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should -Be $true
    }
}
