# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'

Describe 'Test-Login (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Test-Login').Count | Should Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Test-Login'
        $cmd.CmdletBinding | Should Be $true
    }

    It 'declares the -RemoteName parameter' {
        $cmd = Get-Command 'Test-Login'
        $cmd.Parameters.ContainsKey('RemoteName') | Should Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Test-Login' -ErrorAction SilentlyContinue
        $help.Synopsis | Should Not BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Test-Login' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should Be $true
    }
}
