# Generated by tools\Build-PublicUnitTests.ps1. Re-run to regenerate.

$ProjectRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$ModulePath  = Join-Path $ProjectRoot 'GitEasy.psd1'

Describe 'Undo-Changes (unit contract)' {

    BeforeAll {
        Remove-Module GitEasy -Force -ErrorAction SilentlyContinue
        Import-Module $ModulePath -Force
    }

    It 'is exported by the GitEasy module' {
        @(Get-Command -Module GitEasy -Name 'Undo-Changes').Count | Should Be 1
    }

    It 'has CmdletBinding' {
        $cmd = Get-Command 'Undo-Changes'
        $cmd.CmdletBinding | Should Be $true
    }

    It 'supports ShouldProcess (-WhatIf and -Confirm available)' {
        $cmd = Get-Command 'Undo-Changes'
        $cmd.Parameters.ContainsKey('WhatIf')  | Should Be $true
        $cmd.Parameters.ContainsKey('Confirm') | Should Be $true
    }

    It 'declares the -Force parameter' {
        $cmd = Get-Command 'Undo-Changes'
        $cmd.Parameters.ContainsKey('Force') | Should Be $true
    }

    It '-Force is a switch parameter' {
        $cmd = Get-Command 'Undo-Changes'
        $cmd.Parameters['Force'].ParameterType.Name | Should Be 'SwitchParameter'
    }

    It 'declares the -LogPath parameter' {
        $cmd = Get-Command 'Undo-Changes'
        $cmd.Parameters.ContainsKey('LogPath') | Should Be $true
    }

    It 'has a non-empty .SYNOPSIS' {
        $help = Get-Help 'Undo-Changes' -ErrorAction SilentlyContinue
        $help.Synopsis | Should Not BeNullOrEmpty
    }

    It 'has at least one .EXAMPLE in CBH' {
        $help = Get-Help 'Undo-Changes' -Full -ErrorAction SilentlyContinue
        @($help.examples.example).Count -gt 0 | Should Be $true
    }
}
